This should include the latest roles
GSA/openacr-website pull request #49
Opened 2022-01-27 00:40 UTC by mgifford

I needed to delete the old branch. Kinda fumbled this commit after working away on the content over the afternoon.

2022-01-27 15:00 UTC, dmundra requested changes
@mgifford I think I found why the htmlproofer is failing. Rest of the changes would probably good to have @danid123 review.

2022-01-27 15:00 UTC, dmundra commented on _config.yml
> +        url: /vendoor/
Spelling of the permalink `vendoor`

2022-01-27 15:00 UTC, dmundra commented on _config.yml
> +        url: /other/
URL here is singular `other` while the page itself is plural `others`

2022-01-27 15:00 UTC, dmundra commented on _pages/other.md
> +permalink: /others/
I think this should changed to singular or update the filename and the child array to match this one.

2022-01-27 18:48 UTC, dmundra commented on _pages/vendor.md
> +permalink: /vendors/
@mgifford another singular/plural mismatch. Here it is `vendors` but the child menu link is `vendor`

2022-01-28 16:58 UTC, danid123 commented
@mgifford The content looks pretty good. The only thing that seems a little awkward is the Others section for Roles. Were you thinking that there would be more roles listed there? Otherwise I would just change it to match the headline.

2022-01-28 19:17 UTC, mgifford commented
I agree that the others role is awkward.  Who wants to be an other anyways. 

I think that there are other groups though. Could be accessibility organizations. Affinity groups inside of organizations. 

I need to scan through the list of people we highlighted as part of our personas & possible audiences to see if we missed anyone.  

I ultimately broke it into these sections as it seemed to make more sense than giving each role their own page. At least for now.

2022-01-28 20:02 UTC, danid123 commented
Maybe instead of Others it could be Advocates? Or Advocates for People with Disabilities?

2022-01-28 20:49 UTC, mgifford commented
That makes sense. I'll make the changes from others.md, others, Others

to something like advocates.md, advocates & Advocates for Inclusion

"Advocates for People with Disabilities" is just a mouthful.

2022-01-28 22:02 UTC, mgifford commented
> @mgifford I think I found why the htmlproofer is failing. Rest of the changes would probably good to have @danid123 review.

Are there changes that are needed here @dmundra

2022-01-28 22:16 UTC, dmundra commented
> > @mgifford I think I found why the htmlproofer is failing. Rest of the changes would probably good to have @danid123 review.
> 
> Are there changes that are needed here @dmundra

Nope you are good on that front!

2022-01-28 22:24 UTC, danid123 approved these changes
@mgifford I think it looks great. Sometime in the future we might consider adding Agency Section 508 Program Managers (PMs)?

2022-01-28 22:38 UTC, dmundra approved these changes
Approved!

2022-01-28 22:38 UTC, merged